version: 0.2

# AWS CodeBuild buildspec for PurposePath API deployment via Pulumi

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - echo "Installing Pulumi..."
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      - pulumi version
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r coaching/requirements.txt

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      
      # Run tests
      - echo "Running coaching service tests..."
      - cd coaching
      - pip install -r requirements.txt
      - python -m pytest tests/ --tb=short
      - cd ..

  build:
    commands:
      - echo "Build phase started on `date`"
      
      # Deploy Infrastructure
      - echo "Deploying Infrastructure..."
      - cd infrastructure/pulumi
      - pip install -r requirements.txt
      - pulumi stack select dev --create
      - pulumi up --yes --skip-preview
      - cd ../..

      # Deploy Coaching Service
      - echo "Deploying Coaching Service..."
      - cd coaching/pulumi
      - pip install -r requirements.txt
      - pulumi stack select dev --create
      - pulumi up --yes --skip-preview
      - cd ../..

  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Deployment completed successfully."
