AWSTemplateFormatVersion: '2010-09-09'
Description: PurposePath API Custom Domain (dev)

Parameters:
  DomainName:
    Type: String
    Default: api.dev.purposepath.app
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for purposepath.app

Resources:
  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  ApiDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref ApiCertificate
          EndpointType: REGIONAL

  ApiARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiDomain.RegionalHostedZoneId

Outputs:
  DomainName:
    Value: !Ref DomainName
  CertificateArn:
    Value: !Ref ApiCertificate
