AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tiny no-VPC Lambda to validate environment

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return { 'statusCode': 200, 'body': 'ok' }
      Timeout: 3
      MemorySize: 128
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  FunctionName:
    Value: !Ref HelloFunction
