name: Bug report
description: Report a bug to help us improve
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please include reproduction steps.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, inputs, and expected vs actual behavior
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, Python version, service/module
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      render: bash
