"""Shared type definitions for PurposePath API.

Central re-export module for convenient access to all shared types.
Provides strongly-typed definitions for domain IDs, API responses, and AWS service interactions.

Usage:
    from shared.types import UserId, TenantId, APISuccessResponse
    from shared.types import DynamoDBItem, DynamoDBKey
    from shared.types import GoogleUserInfo, StripeCustomer
"""

# Domain ID types and common patterns
# FastAPI response types (API endpoint structures)
from .api_responses import (
    ActivityResponse,
    DeleteResponse,
    GoalCreateRequest,
    GoalListResponse,
    GoalNoteCreateRequest,
    GoalNoteResponse,
    GoalResponse,
    GoalUpdateRequest,
    ReportResponse,
    ReviewResponse,
    StrategyCreateRequest,
    StrategyListResponse,
    StrategyResponse,
    StrategyUpdateRequest,
    StripeSubscriptionData,
    SubscriptionStatusResponse,
    UpdatedResponse,
)

# AWS/DynamoDB types (inheritance pattern)
from .aws import (
    DeleteItemOutputTypeDef,
    DynamoDBItem,
    DynamoDBKey,
    GetItemOutputTypeDef,
    PutItemOutputTypeDef,
    QueryOutputTypeDef,
    ScanOutputTypeDef,
    UpdateItemOutputTypeDef,
)
from .common import (
    ActionId,
    ActionStatus,
    ConversationId,
    ConversationStatus,
    ErrorData,
    GoalId,
    # Common data patterns
    ISODateString,
    JSONDict,
    MessageId,
    PaginationMeta,
    # Pagination patterns
    PaginationParams,
    SessionId,
    StrategyId,
    # Status and state types
    SubscriptionTier,
    # API Response patterns
    SuccessData,
    TenantId,
    # Domain ID types (NewType for strong typing)
    UserId,
    UserStatus,
    create_action_id,
    create_conversation_id,
    create_goal_id,
    create_session_id,
    create_strategy_id,
    create_tenant_id,
    # ID creation utilities
    create_user_id,
)

# External API types (third-party integrations)
from .external import (
    APIGatewayProxyEvent,
    APIGatewayProxyResponse,
    CORSHeaders,
    ExternalAPIError,
    ExternalAPISuccess,
    GoogleAuthState,
    GoogleTokenInfo,
    GoogleUserInfo,
    HTTPHeaders,
    LambdaContext,
    OAuthError,
    OAuthTokenResponse,
    OAuthUserProfile,
    StripeBillingPortalSession,
    StripeCheckoutSession,
    StripeCustomer,
    StripePrice,
    StripeProduct,
    StripeSubscription,
    StripeWebhookEvent,
)

# Repository return types (specific TypedDict for methods)
from .repository import (
    ActionCreateResult,
    ActionGetResult,
    ActionListResult,
    ActionUpdateResult,
    BulkOperationResult,
    BusinessDataCreateResult,
    BusinessDataGetResult,
    BusinessDataUpdateResult,
    ConversationCreateResult,
    ConversationGetResult,
    ConversationListResult,
    ConversationUpdateResult,
    GoalCreateResult,
    GoalGetResult,
    GoalListResult,
    GoalUpdateResult,
    PaginatedRepositoryResult,
    RepositoryMetadata,
    RepositoryResult,
    SessionCreateResult,
    SessionGetResult,
    SessionListResult,
    SessionUpdateResult,
    TransactionResult,
    UserCreateResult,
    UserDeleteResult,
    UserGetResult,
    UserListResult,
    UserUpdateResult,
)

__all__ = [
    "APIGatewayProxyEvent",
    "APIGatewayProxyResponse",
    "ActionCreateResult",
    "ActionGetResult",
    "ActionId",
    "ActionListResult",
    "ActionStatus",
    "ActionUpdateResult",
    "ActivityResponse",
    "BulkOperationResult",
    "BusinessDataCreateResult",
    "BusinessDataGetResult",
    "BusinessDataUpdateResult",
    "CORSHeaders",
    "ConversationCreateResult",
    "ConversationGetResult",
    "ConversationId",
    "ConversationListResult",
    "ConversationStatus",
    "ConversationUpdateResult",
    "DeleteItemOutputTypeDef",
    "DeleteResponse",
    "DynamoDBItem",
    # AWS/DynamoDB types
    "DynamoDBKey",
    "ErrorData",
    "ExternalAPIError",
    "ExternalAPISuccess",
    "GetItemOutputTypeDef",
    "GoalCreateRequest",
    "GoalCreateResult",
    "GoalGetResult",
    "GoalId",
    "GoalListResponse",
    "GoalListResult",
    "GoalNoteCreateRequest",
    "GoalNoteResponse",
    "GoalResponse",
    "GoalUpdateRequest",
    "GoalUpdateResult",
    "GoogleAuthState",
    "GoogleTokenInfo",
    # External API types
    "GoogleUserInfo",
    "HTTPHeaders",
    "ISODateString",
    "JSONDict",
    "LambdaContext",
    "MessageId",
    "OAuthError",
    "OAuthTokenResponse",
    "OAuthUserProfile",
    "PaginatedRepositoryResult",
    "PaginationMeta",
    # Pagination and API Response types
    "PaginationParams",
    "PutItemOutputTypeDef",
    "QueryOutputTypeDef",
    "ReportResponse",
    "RepositoryMetadata",
    # Repository return types
    "RepositoryResult",
    "ReviewResponse",
    "ScanOutputTypeDef",
    "SessionCreateResult",
    "SessionGetResult",
    "SessionId",
    "SessionListResult",
    "SessionUpdateResult",
    "StrategyCreateRequest",
    "StrategyId",
    "StrategyListResponse",
    # FastAPI response types
    "StrategyResponse",
    "StrategyUpdateRequest",
    "StripeBillingPortalSession",
    "StripeCheckoutSession",
    "StripeCustomer",
    "StripePrice",
    "StripeProduct",
    "StripeSubscription",
    "StripeSubscriptionData",
    "StripeWebhookEvent",
    "SubscriptionStatusResponse",
    # Status and state types
    "SubscriptionTier",
    "SuccessData",
    "TenantId",
    "TransactionResult",
    "UpdateItemOutputTypeDef",
    "UpdatedResponse",
    "UserCreateResult",
    "UserDeleteResult",
    "UserGetResult",
    # Domain ID types
    "UserId",
    "UserListResult",
    "UserStatus",
    "UserUpdateResult",
    "create_action_id",
    "create_conversation_id",
    "create_goal_id",
    "create_session_id",
    "create_strategy_id",
    "create_tenant_id",
    # ID creation utilities
    "create_user_id",
]
